project:
  type: book

book:
  title: "Quantitative Social Science Quarterly"
  subtitle: "2026 Volume 1, Issue 1"
  date: today
  sidebar: 
    logo: images/Cover.png

  chapters:
    - index.qmd
    - publisher-letter.qmd
    - feature1.qmd
    - feature2.qmd
    - news-and-reviews.qmd
    - pedagogy-corner.qmd
    - business-of-science.qmd
    - benediction.qmd
  navbar:
    collapse: true
    pinned: true
    search: true

bibliography: refs.bib

format:
  html:
    toc: true
    toc-title: "Chapter contents"
    html-math-method: katex
    theme: 
      light:
        - theme-light.scss
        - styles.scss
      dark:
        - darkly 
        - theme-dark.scss
        - styles.scss
    number-sections: true
    number-depth: 3
