# Benediction {.unnumbered}

> A **benediction** in a Quaker-style church service is a blessing and a bid
farewell. It's a wish to go forth and prosper; to treat yourselves and others
well; and to wish that peace and wisdom be with you. 

---

I wish us all a feeling of empowerment from recognizing that social change is
within reach. It is not enough to just make scientific models of social change
and look at simulations. We have to put our visions into action. Quantitative
social science is but one tool for achieving stable, systemic change towards
sustainable economies of enough, and away from the current destructive economies
of "never enough".

Learned helplessness is a powerful psychological weapon that can make us miss
opportunities for long-term growth because we expect and fear failure. Failure
means we might lose comfort and basic provisions, cause others to question our
sanity and judgement. But I believe failure is just one step on the path to
growth. 

We each have a light. One of the greatest goods in life is to develop that
light in ourselves, and assist others developing theirs. Self-interest and the
golden rule, taken as first principles, can make sustainability go viral when it
is economically superior beyond just being the ethical choice.

