# Introduction: Unspeakable Abuse as a Cover for Transnational Organized Financial Crime 

The main character of this book is Professor Elisa New, currently at Arizona
State University. Before this, she was a fixture and phenom at Harvard
University, where she held the Cabot Chair in American Literature in the English
department. She even got married in the President's residence to Larry Summers,
who in fact was the president of Harvard at the time. Professor New, or
just "Elisa", [](https://brendonbeebe.substack.com/i/187985528/documented-financial-and-institutional-intersections-involving-harvard-and-summers-family)

She is the focus because she executed one important operation at Harvard that
was part of an even larger effort to possibly smuggle artificial intelligence
technology and training data out of the country while laundering money for
Epstein and his colleagues including Leon Black and Ehud Barak. Once the
operation is in full swing, Barak, Epstein, and New may have had sex together,
based on New's email to Epstein on September 2[TK], 2014-Ehud Barak, former
prime minister of Israel, was in town for the 69th United Nations General
Assembly, which would be nothing suspicious for a former head of state.

But Elisa New is but one operative among many who criss-cross the story, enable
the fraud that may be suggested by historical patterns in the emails themselves
and in the events and meetings memorialized in the emails: events like when Bill
Gates ditched his security in New York City before flying to West Palm Beach en
route to Epstein's infamous Little St. James island in the US Virgin Islands.

Consider Epstein's assistant Lesley Groff, who for example emailed Woody Allen's
assistant, Ginevra Tamberi, on December 18, 2013 to clarify plans for a movie
screening at Woody Allen's Manhattan Film Center. Groff joked that if the
screening had to end by 3:30 PM, then "the latest JE could start would be 2pm?
:)". That was December 18, 2013. On May 21, 2014, Lesely emailed Epstein that
Brad Karp is "thrilled about the Woody Allen screening...he is asking if it
would be ok for his daughter to come as well...Please advise if OK for Brad Karp
to bring along his daughter as well. Recall that Karp had to resign as chairman
of the law firm Paul, Weiss law firm recently due to other revelations about his
dealings with Epstein to get his son, David, opportunities with and access to
Woody Allen. Paul, Weiss quickly acquiesced to Trump early in 2025 with a \$10
million settlement to lift restrictions that banned the firm's attorneys from
federal courthouses (TK: WHICH EXEC ORDER?).


## A Brief History of Elisa and "Jeffrey"

![Elisa gushes about how Jeffry's flights are fun because they're not all
about finance the entire trip.](Elisa-on-Jeffreys-Plane-2013.png)

