---
toc-title: "Letter Contents"
---

# Letter from the Publisher {.unnumbered}

<h3 style="font-size:20px; margin-left: 30px;  
           margin-bottom: 20px; text-align: center;">
<b>Ethics and Values to Avoid Acadmic Capture </b>
</h3>

When I visited the Holocaust Museum in Berlin, the ground floor was organized
around the theme of "the geography of terror". Following the so-called final
solution to pursue the policy of jewish extermination, the bureaucracy
crystallized into office buildings occupying several blocks of Berlin's capital
government area. In this book I map out the geography of Jeffrey Epstein's abuse
campaign, focused on Harvard, Cambridge, and Boston, and New York City for this particular
tale. But the main characters in this book are always on the move, from New York
City to outline a deal, then the ranch to finalize the deal, then the island to
celebrate the deal, perhaps.

As social scientists, we need clear ethics and values to avoid untoward
influence not just on the _outcomes_ of our research, but the very _selection_
of scientific problems to work on and the format of the _rituals_ of the
scientific trade. Especially in the academic world, where scientists must bow
before funding agencies and publishers, investing time and money into a process
with highly uncertain payoffs. Few researchers gaining financially at all
from the process. Even fewer are paid what they deserve.

I founded Agile Publishers and started writing and self-publishing to open a
door to escape from confines of academic self-domestication into a world where
science work works for scientists. That means scientists get paid what they're
worth.



'
